export const schema: { name: string; excelKey?: string; type: string; exampleValue: string }[] = [
  { name: "Tầng", excelKey: "floor", type: "string", exampleValue: "17" },
  { name: "Căn số", excelKey: "number", type: "string", exampleValue: "09" },
  { name: "Mã căn", excelKey: "item_code", type: "string", exampleValue: "GMLAK_L5-X17.09" },
  { name: "Tên căn", excelKey: "item_name", type: "string", exampleValue: "L5.17.09" },
  { name: "Loại sản phẩm", excelKey: "product_type", type: "string", exampleValue: "Apartment" },
  { name: "Loại căn hộ", excelKey: "apartment_type", type: "string", exampleValue: "02 bedroom" },
  { name: "Phòng ngủ", excelKey: "bedroom", type: "string", exampleValue: "bedroom" },
  { name: "Hướng Balcony VN", excelKey: "balcony_direction_vn", type: "string", exampleValue: "Tây Bắc - Đông Bắc" },
  {
    name: "Hướng Balcony EN",
    excelKey: "balcony_direction_en",
    type: "string",
    exampleValue: "North West - North East",
  },
  { name: "View 3D balcony", excelKey: "view_3d_balcony", type: "string", exampleValue: "balcony_view_url" },
  { name: "View VN", excelKey: "view_vn", type: "string", exampleValue: "Botanic Garden" },
  { name: "View EN", excelKey: "view_en", type: "string", exampleValue: "Botanic Garden" },
  {
    name: "Hướng cửa trước VN",
    excelKey: "front_door_direction_vn",
    type: "string",
    exampleValue: "front_door_direction",
  },
  {
    name: "Hướng cửa trước EN",
    excelKey: "front_door_direction_en",
    type: "string",
    exampleValue: "front_door_direction_en",
  },
  { name: "Biệt thự", excelKey: "villa_type", type: "string", exampleValue: "villa_type" },
  { name: "Số thửa đất", excelKey: "land_lot_number", type: "string", exampleValue: "253" },
  { name: "Tên thửa đất", excelKey: "land_lot_name", type: "string", exampleValue: "HH4-3" },
  { name: "Lô", excelKey: "biz_unit_plan_code", type: "string", exampleValue: "biz_unit_plan_code" },
  { name: "Diện tích đất", excelKey: "land_area", type: "string", exampleValue: "lot_area" },
  { name: "Diện tích tim tường", excelKey: "wall_area", type: "string", exampleValue: "117.05" },
  { name: "Diện tích thông thủy", excelKey: "clear_area", type: "string", exampleValue: "107.51" },
  { name: "Giá quyền sử dụng đất", excelKey: "land_use_right_price", type: "string", exampleValue: " 875,776,460 " },
  { name: "Đơn giá đất", excelKey: "land_unit_price", type: "string", exampleValue: " 160,000,000 " },
  { name: "Diện tích xây dựng", excelKey: "construction_area", type: "string", exampleValue: "construction_area" },
  {
    name: "Diện tích sàn xây dựng (tạm tính)",
    excelKey: "gross_floor_area",
    type: "string",
    exampleValue: "gross_floor_area",
  },
  { name: "Thửa đất số", excelKey: "unit_land_lot_number", type: "string", exampleValue: "unit_land_lot_number" },
  { name: "Tờ bản đồ", excelKey: "unit_map_sheet_number", type: "string", exampleValue: "unit_map_sheet_number" },
  {
    name: "Số tầng của Sản Phẩm",
    excelKey: "unit_number_of_floor",
    type: "string",
    exampleValue: "unit_number_of_floor",
  },
  { name: "Đã bao gồm KPBT & VAT", excelKey: "includes_kpbt_vat", type: "string", exampleValue: "TRUE" },
  { name: "% KPBT", excelKey: "kpbt_percentage", type: "string", exampleValue: "2" },
  { name: "F2", excelKey: "f2", type: "string", exampleValue: "TRUE" },
  { name: "Trạng thái", excelKey: "status", type: "string", exampleValue: "unavailable" },
  { name: "Ngày MOC", excelKey: "moc_date", type: "string", exampleValue: "23/06/2023" },
  { name: "Giá trị phí bảo trì", excelKey: "maintenance_fee_value", type: "string", exampleValue: " 120,500,000 " },
  { name: "Giá thuê/m2", excelKey: "rent_price_per_sqm", type: "string", exampleValue: " 122,500,000 " },
  { name: "Số tháng cam kết cho thuê", excelKey: "committed_rental_months", type: "string", exampleValue: "12" },
  { name: "Số tháng vay HTLS", excelKey: "htls_loan_months", type: "string", exampleValue: "12" },
  { name: "% HDMB F1", excelKey: "hdmb_f1_percentage", type: "string", exampleValue: "5" },
  { name: "Mã dự án theo căn", excelKey: "project_code_by_unit", type: "string", exampleValue: "GMLAK" },
  { name: "Mã warehouse", excelKey: "warehouse_code", type: "string", exampleValue: "HPI_02" },
  {
    name: "Mã căn linkable bên trái",
    excelKey: "left_linkable_unit_code",
    type: "string",
    exampleValue: "left_linkable",
  },
  { name: "Mã linkable", excelKey: "linkable_code", type: "string", exampleValue: "linkable_code" },
  {
    name: "Mã căn linkable bên phải",
    excelKey: "right_linkable_unit_code",
    type: "string",
    exampleValue: "right_linkable",
  },
  {
    name: "Vị trí unit hiển thị trên Stacking Plan",
    excelKey: "sp_display_number",
    type: "string",
    exampleValue: "sp_display_number",
  },
  { name: "Finance Unit Type", excelKey: "finance_unit_type", type: "string", exampleValue: "post_action_type" },
]
